package minipipeline

import (
	"github.com/ooni/probe-cli/v3/internal/model"
	"github.com/ooni/probe-cli/v3/internal/optional"
)

// Measurement is the canonical measurement structure assumed
// by the probe-engine mini processing pipeline.
type Measurement struct {
	// Input contains the input we measured.
	Input string `json:"input"`

	// TestKeys contains the test-specific measurements.
	TestKeys optional.Value[*MeasurementTestKeys] `json:"test_keys"`
}

// MeasurementTestKeys is the canonical container for observations
// generated by most OONI experiments. This is the data format ingested
// by this package for generating, e.g., [*WebEndpointObservations]
type MeasurementTestKeys struct {
	// Control contains the OPTIONAL TH response.
	Control optional.Value[*model.THResponse] `json:"control"`

	// NetworkEvents contains I/O events.
	NetworkEvents []*model.ArchivalNetworkEvent `json:"network_events"`

	// Queries contains the DNS queries results.
	Queries []*model.ArchivalDNSLookupResult `json:"queries"`

	// Requests contains HTTP request results.
	Requests []*model.ArchivalHTTPRequestResult `json:"requests"`

	// TCPConnect contains the TCP connect results.
	TCPConnect []*model.ArchivalTCPConnectResult `json:"tcp_connect"`

	// TLSHandshakes contains the TLS handshakes results.
	TLSHandshakes []*model.ArchivalTLSOrQUICHandshakeResult `json:"tls_handshakes"`

	// QUICHandshakes contains the QUIC handshakes results.
	QUICHandshakes []*model.ArchivalTLSOrQUICHandshakeResult `json:"quic_handshakes"`

	// XControlRequest contains the OPTIONAL TH request.
	XControlRequest optional.Value[*model.THRequest] `json:"x_control_request"`
}
