#!/bin/bash

set -euo pipefail

__install_extra="build-tools;32.0.0 platforms;android-31"

__ndk_version=$(cat ./NDKVERSION)

ANDROID_HOME=$(./MOBILE/android/home)

__sdkmanager=$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager
if [[ ! -x $__sdkmanager ]]; then
	echo "FATAL: expected to find sdkmanager at $__sdkmanager, but found nothing" 1>&2
	echo "HINT: run ./MOBILE/android/setup to (re)install the SDK" 1>&2
	exit 1
fi

set -x
echo "Yes" | $__sdkmanager --install $__install_extra "ndk;$__ndk_version"
