#!/bin/sh

# print the fullpath of the go/gomobile we're using so that it's part
# of the build logs and we can easily increase our confidence
# that we are using the right go/gomobile binary.

echo -n "$0: checking for go... "
go=`command -v go`
if [ -z $go ]; then
    echo "not found"
    exit 1
fi
echo "$go"

echo -n "$0: checking for gomobile... "
gomobile=`command -v gomobile`
if [ -z $go ]; then
    echo "not found"
    exit 1
fi
echo "$gomobile"

set -x
$gomobile "$@"
