#!/bin/bash

set -euo pipefail

nocheck=0
if [[ $# -eq 1 && $1 == "--no-check" ]]; then
	nocheck=1
fi

system=$(uname -s)
case $system in
Linux)
	__sdk_dir=$HOME/Android/Sdk
	;;
Darwin)
	__sdk_dir=$HOME/Library/Android/sdk
	;;
*)
	echo "FATAL: unsupported operating system: $system" 1>&2
	exit 1
	;;
esac

ANDROID_HOME=${ANDROID_HOME:-$__sdk_dir}
if [[ $nocheck == 0 && ! -d $ANDROID_HOME ]]; then
	echo "FATAL: expected to find android SDK at $ANDROID_HOME, but found nothing" 1>&2
	echo "HINT: run ./MOBILE/android/setup to (re)install the SDK" 1>&2
	exit 1
fi
echo $ANDROID_HOME
