#!/bin/bash
set -euxo pipefail
reporoot=$(dirname $(dirname $(dirname $(realpath $0))))
rm -rf $reporoot/MOBILE/android/keystore.jks
keystorepassword=ooniprobe
printf "${keystorepassword}\n${keystorepassword}\n\n\n\n\n\n\nyes\n" |
	keytool -genkey -v -keystore $reporoot/MOBILE/android/keystore.jks -keyalg RSA \
		-keysize 2048 -validity 7 -alias key0
