// Code generated by go generate; DO NOT EDIT.
// Generated: 2021-09-28 18:13:54.317744 +0200 CEST m=+0.409422292

package netxlite

import "golang.org/x/sys/windows"

const (
	ECONNREFUSED    = windows.WSAECONNREFUSED
	ECONNRESET      = windows.WSAECONNRESET
	EHOSTUNREACH    = windows.WSAEHOSTUNREACH
	ETIMEDOUT       = windows.WSAETIMEDOUT
	EAFNOSUPPORT    = windows.WSAEAFNOSUPPORT
	EADDRINUSE      = windows.WSAEADDRINUSE
	EADDRNOTAVAIL   = windows.WSAEADDRNOTAVAIL
	EISCONN         = windows.WSAEISCONN
	EFAULT          = windows.WSAEFAULT
	EBADF           = windows.WSAEBADF
	ECONNABORTED    = windows.WSAECONNABORTED
	EALREADY        = windows.WSAEALREADY
	EDESTADDRREQ    = windows.WSAEDESTADDRREQ
	EINTR           = windows.WSAEINTR
	EINVAL          = windows.WSAEINVAL
	EMSGSIZE        = windows.WSAEMSGSIZE
	ENETDOWN        = windows.WSAENETDOWN
	ENETRESET       = windows.WSAENETRESET
	ENETUNREACH     = windows.WSAENETUNREACH
	ENOBUFS         = windows.WSAENOBUFS
	ENOPROTOOPT     = windows.WSAENOPROTOOPT
	ENOTSOCK        = windows.WSAENOTSOCK
	ENOTCONN        = windows.WSAENOTCONN
	EWOULDBLOCK     = windows.WSAEWOULDBLOCK
	EACCES          = windows.WSAEACCES
	EPROTONOSUPPORT = windows.WSAEPROTONOSUPPORT
	EPROTOTYPE      = windows.WSAEPROTOTYPE
)
