#!/bin/bash
set -euo pipefail
__version=$(date -u +%Y.%m.%d-%H%M%S)
__release="${1:-$(git describe --tags || echo '0.0.0-dev')}"

# Save original variable before substitution so we can unit test it
__orig=${__release}

# determine whether we're publishing to a release or to rolling
#
# when publishing to rolling the __release variable is like: 'v3.19.0-alpha-27-g4678578b'
# otherwise it's like `v3.19.0`, `v3.19.0-alpha`, or `v3.19.0-beta.555`.
if ! [[ $__release =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-z]+(\.[0-9]+)?)?$ ]]; then
	__release=rolling
fi

if [[ ${CREATE_POD_SPECS_DEBUG:-0} == 1 ]]; then
	echo "$__orig -> $__release"
	exit 0
fi

for name in libcrypto libevent libssl libtor libz oonimkall; do
	cat ./MOBILE/ios/${name}-template.podspec | sed -e "s/@VERSION@/$__version/g" \
		-e "s/@RELEASE@/$__release/g" >./MOBILE/ios/${name}.podspec
done
