#!/bin/bash
set -euo pipefail
__version=$(date -u +%Y.%m.%d-%H%M%S)
__release=$(git describe --tags || echo '0.0.0-dev')

for name in libcrypto libevent libssl libtor libz oonimkall; do
	cat ./MOBILE/ios/${name}-template.podspec | sed -e "s/@VERSION@/$__version/g" \
		-e "s/@RELEASE@/$__release/g" >./MOBILE/ios/${name}.podspec
done
