// Code generated by go generate; DO NOT EDIT.
// 2021-02-24 10:30:26.157728505 +0100 CET m=+0.618961215

package ooapi

//go:generate go run ./internal/generator

// PsiphonConfigCaller represents any type exposing a method
// like PsiphonConfigAPI.WithToken.
type PsiphonConfigCloner interface {
	WithToken(token string) PsiphonConfigCaller
}

// TorTargetsCaller represents any type exposing a method
// like TorTargetsAPI.WithToken.
type TorTargetsCloner interface {
	WithToken(token string) TorTargetsCaller
}
