// Code generated by go generate; DO NOT EDIT.
// 2021-02-23 14:43:01.876066 +0100 CET m=+2.482344619

package ooapi

//go:generate go run ./internal/generator

// PsiphonConfigCloner abstracts PsiphonConfigAPI's cloner behavior.
type PsiphonConfigCloner interface {
	WithToken(token string) PsiphonConfigCaller
}

// TorTargetsCloner abstracts TorTargetsAPI's cloner behavior.
type TorTargetsCloner interface {
	WithToken(token string) TorTargetsCaller
}
