// Code generated by go generate; DO NOT EDIT.
// 2021-02-23 13:44:06.957386 +0100 CET m=+1.789418240

package ooapi

//go:generate go run ./internal/generator

import (
	"context"

	"github.com/ooni/probe-cli/v3/internal/engine/ooapi/apimodel"
)

type FakeCheckReportIDAPI struct {
	Err      error
	Response *apimodel.CheckReportIDResponse
}

func (fapi *FakeCheckReportIDAPI) Call(ctx context.Context, req *apimodel.CheckReportIDRequest) (*apimodel.CheckReportIDResponse, error) {
	return fapi.Response, fapi.Err
}

var (
	_ CheckReportIDCaller = &FakeCheckReportIDAPI{}
)

type FakeCheckInAPI struct {
	Err      error
	Response *apimodel.CheckInResponse
}

func (fapi *FakeCheckInAPI) Call(ctx context.Context, req *apimodel.CheckInRequest) (*apimodel.CheckInResponse, error) {
	return fapi.Response, fapi.Err
}

var (
	_ CheckInCaller = &FakeCheckInAPI{}
)

type FakeLoginAPI struct {
	Err      error
	Response *apimodel.LoginResponse
}

func (fapi *FakeLoginAPI) Call(ctx context.Context, req *apimodel.LoginRequest) (*apimodel.LoginResponse, error) {
	return fapi.Response, fapi.Err
}

var (
	_ LoginCaller = &FakeLoginAPI{}
)

type FakeMeasurementMetaAPI struct {
	Err      error
	Response *apimodel.MeasurementMetaResponse
}

func (fapi *FakeMeasurementMetaAPI) Call(ctx context.Context, req *apimodel.MeasurementMetaRequest) (*apimodel.MeasurementMetaResponse, error) {
	return fapi.Response, fapi.Err
}

var (
	_ MeasurementMetaCaller = &FakeMeasurementMetaAPI{}
)

type FakeRegisterAPI struct {
	Err      error
	Response *apimodel.RegisterResponse
}

func (fapi *FakeRegisterAPI) Call(ctx context.Context, req *apimodel.RegisterRequest) (*apimodel.RegisterResponse, error) {
	return fapi.Response, fapi.Err
}

var (
	_ RegisterCaller = &FakeRegisterAPI{}
)

type FakeTestHelpersAPI struct {
	Err      error
	Response apimodel.TestHelpersResponse
}

func (fapi *FakeTestHelpersAPI) Call(ctx context.Context, req *apimodel.TestHelpersRequest) (apimodel.TestHelpersResponse, error) {
	return fapi.Response, fapi.Err
}

var (
	_ TestHelpersCaller = &FakeTestHelpersAPI{}
)

type FakePsiphonConfigAPI struct {
	WithResult PsiphonConfigCaller
	Err        error
	Response   apimodel.PsiphonConfigResponse
}

func (fapi *FakePsiphonConfigAPI) Call(ctx context.Context, req *apimodel.PsiphonConfigRequest) (apimodel.PsiphonConfigResponse, error) {
	return fapi.Response, fapi.Err
}

func (fapi *FakePsiphonConfigAPI) WithToken(token string) PsiphonConfigCaller {
	return fapi.WithResult
}

var (
	_ PsiphonConfigCaller = &FakePsiphonConfigAPI{}
	_ PsiphonConfigCloner = &FakePsiphonConfigAPI{}
)

type FakeTorTargetsAPI struct {
	WithResult TorTargetsCaller
	Err        error
	Response   apimodel.TorTargetsResponse
}

func (fapi *FakeTorTargetsAPI) Call(ctx context.Context, req *apimodel.TorTargetsRequest) (apimodel.TorTargetsResponse, error) {
	return fapi.Response, fapi.Err
}

func (fapi *FakeTorTargetsAPI) WithToken(token string) TorTargetsCaller {
	return fapi.WithResult
}

var (
	_ TorTargetsCaller = &FakeTorTargetsAPI{}
	_ TorTargetsCloner = &FakeTorTargetsAPI{}
)

type FakeURLsAPI struct {
	Err      error
	Response *apimodel.URLsResponse
}

func (fapi *FakeURLsAPI) Call(ctx context.Context, req *apimodel.URLsRequest) (*apimodel.URLsResponse, error) {
	return fapi.Response, fapi.Err
}

var (
	_ URLsCaller = &FakeURLsAPI{}
)

type FakeOpenReportAPI struct {
	Err      error
	Response *apimodel.OpenReportResponse
}

func (fapi *FakeOpenReportAPI) Call(ctx context.Context, req *apimodel.OpenReportRequest) (*apimodel.OpenReportResponse, error) {
	return fapi.Response, fapi.Err
}

var (
	_ OpenReportCaller = &FakeOpenReportAPI{}
)

type FakeSubmitMeasurementAPI struct {
	Err      error
	Response *apimodel.SubmitMeasurementResponse
}

func (fapi *FakeSubmitMeasurementAPI) Call(ctx context.Context, req *apimodel.SubmitMeasurementRequest) (*apimodel.SubmitMeasurementResponse, error) {
	return fapi.Response, fapi.Err
}

var (
	_ SubmitMeasurementCaller = &FakeSubmitMeasurementAPI{}
)
