// Code generated by go generate; DO NOT EDIT.
// 2021-02-23 11:13:45.126343 +0100 CET m=+0.425908837

package ooapi

//go:generate go run ./internal/generator

import (
	"io"
	"io/ioutil"
	"net/http"

	"github.com/ooni/probe-cli/v3/internal/engine/ooapi/apimodel"
)

func (api *CheckReportIDAPI) newResponse(resp *http.Response, err error) (*apimodel.CheckReportIDResponse, error) {
	if err != nil {
		return nil, err
	}
	if resp.StatusCode == 401 {
		return nil, ErrUnauthorized
	}
	if resp.StatusCode != 200 {
		return nil, newHTTPFailure(resp.StatusCode)
	}
	defer resp.Body.Close()
	reader := io.LimitReader(resp.Body, 4<<20)
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	out := &apimodel.CheckReportIDResponse{}
	if err := api.jsonCodec().Decode(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (api *CheckInAPI) newResponse(resp *http.Response, err error) (*apimodel.CheckInResponse, error) {
	if err != nil {
		return nil, err
	}
	if resp.StatusCode == 401 {
		return nil, ErrUnauthorized
	}
	if resp.StatusCode != 200 {
		return nil, newHTTPFailure(resp.StatusCode)
	}
	defer resp.Body.Close()
	reader := io.LimitReader(resp.Body, 4<<20)
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	out := &apimodel.CheckInResponse{}
	if err := api.jsonCodec().Decode(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (api *LoginAPI) newResponse(resp *http.Response, err error) (*apimodel.LoginResponse, error) {
	if err != nil {
		return nil, err
	}
	if resp.StatusCode == 401 {
		return nil, ErrUnauthorized
	}
	if resp.StatusCode != 200 {
		return nil, newHTTPFailure(resp.StatusCode)
	}
	defer resp.Body.Close()
	reader := io.LimitReader(resp.Body, 4<<20)
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	out := &apimodel.LoginResponse{}
	if err := api.jsonCodec().Decode(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (api *MeasurementMetaAPI) newResponse(resp *http.Response, err error) (*apimodel.MeasurementMetaResponse, error) {
	if err != nil {
		return nil, err
	}
	if resp.StatusCode == 401 {
		return nil, ErrUnauthorized
	}
	if resp.StatusCode != 200 {
		return nil, newHTTPFailure(resp.StatusCode)
	}
	defer resp.Body.Close()
	reader := io.LimitReader(resp.Body, 4<<20)
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	out := &apimodel.MeasurementMetaResponse{}
	if err := api.jsonCodec().Decode(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (api *RegisterAPI) newResponse(resp *http.Response, err error) (*apimodel.RegisterResponse, error) {
	if err != nil {
		return nil, err
	}
	if resp.StatusCode == 401 {
		return nil, ErrUnauthorized
	}
	if resp.StatusCode != 200 {
		return nil, newHTTPFailure(resp.StatusCode)
	}
	defer resp.Body.Close()
	reader := io.LimitReader(resp.Body, 4<<20)
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	out := &apimodel.RegisterResponse{}
	if err := api.jsonCodec().Decode(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (api *TestHelpersAPI) newResponse(resp *http.Response, err error) (apimodel.TestHelpersResponse, error) {
	if err != nil {
		return nil, err
	}
	if resp.StatusCode == 401 {
		return nil, ErrUnauthorized
	}
	if resp.StatusCode != 200 {
		return nil, newHTTPFailure(resp.StatusCode)
	}
	defer resp.Body.Close()
	reader := io.LimitReader(resp.Body, 4<<20)
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	out := apimodel.TestHelpersResponse{}
	if err := api.jsonCodec().Decode(data, &out); err != nil {
		return nil, err
	}
	if out == nil {
		return nil, ErrJSONLiteralNull
	}
	return out, nil
}

func (api *PsiphonConfigAPI) newResponse(resp *http.Response, err error) (apimodel.PsiphonConfigResponse, error) {
	if err != nil {
		return nil, err
	}
	if resp.StatusCode == 401 {
		return nil, ErrUnauthorized
	}
	if resp.StatusCode != 200 {
		return nil, newHTTPFailure(resp.StatusCode)
	}
	defer resp.Body.Close()
	reader := io.LimitReader(resp.Body, 4<<20)
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	out := apimodel.PsiphonConfigResponse{}
	if err := api.jsonCodec().Decode(data, &out); err != nil {
		return nil, err
	}
	if out == nil {
		return nil, ErrJSONLiteralNull
	}
	return out, nil
}

func (api *TorTargetsAPI) newResponse(resp *http.Response, err error) (apimodel.TorTargetsResponse, error) {
	if err != nil {
		return nil, err
	}
	if resp.StatusCode == 401 {
		return nil, ErrUnauthorized
	}
	if resp.StatusCode != 200 {
		return nil, newHTTPFailure(resp.StatusCode)
	}
	defer resp.Body.Close()
	reader := io.LimitReader(resp.Body, 4<<20)
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	out := apimodel.TorTargetsResponse{}
	if err := api.jsonCodec().Decode(data, &out); err != nil {
		return nil, err
	}
	if out == nil {
		return nil, ErrJSONLiteralNull
	}
	return out, nil
}

func (api *URLsAPI) newResponse(resp *http.Response, err error) (*apimodel.URLsResponse, error) {
	if err != nil {
		return nil, err
	}
	if resp.StatusCode == 401 {
		return nil, ErrUnauthorized
	}
	if resp.StatusCode != 200 {
		return nil, newHTTPFailure(resp.StatusCode)
	}
	defer resp.Body.Close()
	reader := io.LimitReader(resp.Body, 4<<20)
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	out := &apimodel.URLsResponse{}
	if err := api.jsonCodec().Decode(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (api *OpenReportAPI) newResponse(resp *http.Response, err error) (*apimodel.OpenReportResponse, error) {
	if err != nil {
		return nil, err
	}
	if resp.StatusCode == 401 {
		return nil, ErrUnauthorized
	}
	if resp.StatusCode != 200 {
		return nil, newHTTPFailure(resp.StatusCode)
	}
	defer resp.Body.Close()
	reader := io.LimitReader(resp.Body, 4<<20)
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	out := &apimodel.OpenReportResponse{}
	if err := api.jsonCodec().Decode(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (api *SubmitMeasurementAPI) newResponse(resp *http.Response, err error) (*apimodel.SubmitMeasurementResponse, error) {
	if err != nil {
		return nil, err
	}
	if resp.StatusCode == 401 {
		return nil, ErrUnauthorized
	}
	if resp.StatusCode != 200 {
		return nil, newHTTPFailure(resp.StatusCode)
	}
	defer resp.Body.Close()
	reader := io.LimitReader(resp.Body, 4<<20)
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	out := &apimodel.SubmitMeasurementResponse{}
	if err := api.jsonCodec().Decode(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
