#!/bin/bash
# Adapted from https://github.com/guardianproject/tor-android
# SPDX-License-Identifier: BSD-3-Clause

set -euxo pipefail

mydir=$(dirname $(realpath $0))

pkgbuild() (
	local workdir=$(mktemp -d)

	cd $workdir

	curl -fsSLO https://www.openssl.org/source/openssl-1.1.1s.tar.gz
	local expected_sha256="c5ac01e760ee6ff0dab61d6b2bbd30146724d063eb322180c6f18a6f74e4b6aa"
	local real_sha256=$(sha256sum openssl-1.1.1s.tar.gz | awk '{print $1}')
	if [[ $expected_sha256 != $real_sha256 ]]; then
		echo "FATAL: expected $expected_sha256 got $real_sha256" 1>&2
		exit 1
	fi

	tar -xf openssl-1.1.1s.tar.gz
	cd openssl-1.1.1s

	git apply $mydir/*.patch

	export CFLAGS="${CFLAGS:-} -Wno-macro-redefined"
	./Configure \
		no-comp no-dtls no-ec2m no-psk no-srp no-ssl2 no-ssl3 \
		no-camellia no-idea no-md2 no-md4 no-mdc2 no-rc2 no-rc4 no-rc5 no-rmd160 no-whirlpool \
		no-dso no-hw no-ui-console \
		no-shared no-unit-test \
		$OPENSSL_COMPILER \
		--prefix=/ \
		--openssldir=/

	make -j$(nproc)

	make DESTDIR=$DESTDIR install_dev
	rm -rf $DESTDIR/lib/pkgconfig
)

pkgbuild
