#!/bin/bash
set -euo pipefail

USAGE="usage: $0 amd64|arm64 [package...]"

if [[ $# < 1 ]]; then
	echo $USAGE 1>&2
	exit 1
fi
GOARCH=$1
shift

topdir=$(dirname $(dirname $(realpath $0)))

case "$GOARCH" in
amd64)
	DARWIN_ARCH=x86_64
	export OPENSSL_COMPILER=darwin64-x86_64-cc
	;;
arm64)
	DARWIN_ARCH=$GOARCH
	export OPENSSL_COMPILER=darwin64-arm64-cc
	;;
*)
	echo $USAGE 1>&2
	exit 1
	;;
esac

export CC="clang -arch $DARWIN_ARCH"
export DESTDIR=$topdir/internal/libtor/darwin/$GOARCH

while [[ $# > 0 ]]; do
	$topdir/CDEPS/$1/build
	shift
done
