#!/bin/bash

set -euo pipefail

if [[ $# -ne 1 ]]; then
	echo "" 1>&2
	echo "Compiler for a Go PACKAGE producing linux/amd64 binaries in the" 1>&2
	echo "top-level directory (should not be used for releasing). We'll build" 1>&2
	echo "and link PACKAGE with a libtor.a compiled for linux/amd64." 1>&2
	echo "" 1>&2
	echo "usage: $0 PACKAGE..." 1>&2
	echo "" 1>&2
	echo "Features:" 1>&2
	echo "" 1>&2
	echo "* automatically sets -tags=ooni_psiphon_config when possible;" 1>&2
	echo "" 1>&2
	echo "* if GOLANG_EXTRA_FLAGS is set, pass it to the Go compiler." 1>&2
	echo "" 1>&2
	echo "* automatically compile and links with libtor.a compiled for linux/amd64." 1>&2
	echo "" 1>&2
	echo "Example:" 1>&2
	echo "" 1>&2
	echo "  ./CLI/go-build-linux-amd64-embed-tor ./internal/cmd/miniooni" 1>&2
	echo "" 1>&2
	exit 1
fi

if [[ -f ./internal/engine/psiphon-config.json.age &&
	-f ./internal/engine/psiphon-config.key ]]; then
	build_tags="ooni_psiphon_config,ooni_libtor"
else
	build_tags="ooni_libtor"
fi

./CDEPS/build-linux-amd64 zlib openssl libevent tor

set -x
for pkg in "$@"; do
	go build -tags=$build_tags -ldflags="-s -w" ${GOLANG_EXTRA_FLAGS:-} $pkg
done
