// Code generated by go generate; DO NOT EDIT.
// Generated: 2021-09-07 14:56:43.179707 +0200 CEST m=+0.114644626

package errorsx

import "golang.org/x/sys/windows"

const (
	ECANCELED       = windows.ECANCELED
	ECONNREFUSED    = windows.ECONNREFUSED
	ECONNRESET      = windows.ECONNRESET
	EHOSTUNREACH    = windows.EHOSTUNREACH
	ETIMEDOUT       = windows.ETIMEDOUT
	EAFNOSUPPORT    = windows.EAFNOSUPPORT
	EADDRINUSE      = windows.EADDRINUSE
	EADDRNOTAVAIL   = windows.EADDRNOTAVAIL
	EISCONN         = windows.EISCONN
	EFAULT          = windows.EFAULT
	EBADF           = windows.EBADF
	ECONNABORTED    = windows.ECONNABORTED
	EALREADY        = windows.EALREADY
	EDESTADDRREQ    = windows.EDESTADDRREQ
	EINTR           = windows.EINTR
	EINVAL          = windows.EINVAL
	EMSGSIZE        = windows.EMSGSIZE
	ENETDOWN        = windows.ENETDOWN
	ENETRESET       = windows.ENETRESET
	ENETUNREACH     = windows.ENETUNREACH
	ENOBUFS         = windows.ENOBUFS
	ENOPROTOOPT     = windows.ENOPROTOOPT
	ENOTSOCK        = windows.ENOTSOCK
	ENOTCONN        = windows.ENOTCONN
	EWOULDBLOCK     = windows.EWOULDBLOCK
	EACCES          = windows.EACCES
	EPROTONOSUPPORT = windows.EPROTONOSUPPORT
	EPROTOTYPE      = windows.EPROTOTYPE
)
