#!/bin/bash
set -euo pipefail

if [[ $# < 1 ]]; then
	echo "usage: $0 386|amd64 [package...]" 1>&2
	exit 1
fi
GOARCH=$1
shift

case "$GOARCH" in
amd64)
	export CONFIGURE_HOST=x86_64-w64-mingw32
	export CC=x86_64-w64-mingw32-gcc
	export WINDRES=x86_64-w64-mingw32-windres
	export OPENSSL_COMPILER=mingw64
	;;
386)
	export CONFIGURE_HOST=i686-w64-mingw32
	export CC=i686-w64-mingw32-gcc
	export WINDRES=i686-w64-mingw32-windres
	export OPENSSL_COMPILER=mingw
	;;
*)
	echo "FATAL: unsupported architecture" 1>&2
	exit 1
	;;
esac

topdir=$(dirname $(dirname $(realpath $0)))

export DESTDIR=$topdir/CDEPS/dist/windows/$GOARCH

while [[ $# > 0 ]]; do
	(
		# The libevent configure script fails to terminate successfully
		# unless we force its linking policies with specific libs.
		if [[ -f $topdir/CDEPS/$1/mingw-libs ]]; then
			export LIBS=$(cat $topdir/CDEPS/$1/mingw-libs)
		fi
		$topdir/CDEPS/$1/build
	)
	shift
done
