part of 'app.dart';

const kDarkColors = [
  {"name": "color_black", "value": "ffffff"},
  {"name": "color_white", "value": "1b1b1b"},
  {"name": "color_base", "value": "056aa6"},
  {"name": "color_gray0", "value": "343a40"},
  {"name": "color_gray1", "value": "f1f3f5"},
  {"name": "color_gray2", "value": "e9ecef"},
  {"name": "color_gray3", "value": "dee2e6"},
  {"name": "color_gray4", "value": "ced4da"},
  {"name": "color_gray5", "value": "adb5bd"},
  {"name": "color_gray6", "value": "868e96"},
  {"name": "color_gray7", "value": "ced4da"},
  {"name": "color_gray8", "value": "343a40"},
  {"name": "color_gray9", "value": "f8f9fa"},
  {"name": "color_blue0", "value": "e7f5ff"},
  {"name": "color_blue1", "value": "c9e8ff"},
  {"name": "color_blue2", "value": "94d1ff"},
  {"name": "color_blue3", "value": "5db8fe"},
  {"name": "color_blue4", "value": "37a6ed"},
  {"name": "color_blue5", "value": "0588cb"},
  {"name": "color_blue6", "value": "0f77b8"},
  {"name": "color_blue7", "value": "056aa6"},
  {"name": "color_blue8", "value": "005f9c"},
  {"name": "color_blue9", "value": "005a99"},
  {"name": "color_indigo0", "value": "edf2ff"},
  {"name": "color_indigo1", "value": "dbe4ff"},
  {"name": "color_indigo2", "value": "bac8ff"},
  {"name": "color_indigo3", "value": "91a7ff"},
  {"name": "color_indigo4", "value": "748ffc"},
  {"name": "color_indigo5", "value": "5c7cfa"},
  {"name": "color_indigo6", "value": "4c6ef5"},
  {"name": "color_indigo7", "value": "4263eb"},
  {"name": "color_indigo8", "value": "3b5bdb"},
  {"name": "color_indigo9", "value": "364fc7"},
  {"name": "color_violet0", "value": "f3f0ff"},
  {"name": "color_violet1", "value": "e5dbff"},
  {"name": "color_violet2", "value": "d0bfff"},
  {"name": "color_violet3", "value": "b197fc"},
  {"name": "color_violet4", "value": "9775fa"},
  {"name": "color_violet5", "value": "845ef7"},
  {"name": "color_violet6", "value": "7950f2"},
  {"name": "color_violet7", "value": "7048e8"},
  {"name": "color_violet8", "value": "6741d9"},
  {"name": "color_violet9", "value": "5f3dc4"},
  {"name": "color_fuchsia0", "value": "f8f0fc"},
  {"name": "color_fuchsia1", "value": "f3d9fa"},
  {"name": "color_fuchsia2", "value": "eebefa"},
  {"name": "color_fuchsia3", "value": "e599f7"},
  {"name": "color_fuchsia4", "value": "da77f2"},
  {"name": "color_fuchsia5", "value": "cc5de8"},
  {"name": "color_fuchsia6", "value": "be4bdb"},
  {"name": "color_fuchsia7", "value": "ae3ec9"},
  {"name": "color_fuchsia8", "value": "9c36b5"},
  {"name": "color_fuchsia9", "value": "862e9c"},
  {"name": "color_pink0", "value": "fff0f6"},
  {"name": "color_pink1", "value": "ffdeeb"},
  {"name": "color_pink2", "value": "fcc2d7"},
  {"name": "color_pink3", "value": "faa2c1"},
  {"name": "color_pink4", "value": "f783ac"},
  {"name": "color_pink5", "value": "f06595"},
  {"name": "color_pink6", "value": "e64980"},
  {"name": "color_pink7", "value": "d6336c"},
  {"name": "color_pink8", "value": "c2255c"},
  {"name": "color_pink9", "value": "a61e4d"},
  {"name": "color_red0", "value": "fff5f5"},
  {"name": "color_red1", "value": "ffe3e3"},
  {"name": "color_red2", "value": "ffc9c9"},
  {"name": "color_red3", "value": "ffa8a8"},
  {"name": "color_red4", "value": "ff8787"},
  {"name": "color_red5", "value": "ff6b6b"},
  {"name": "color_red6", "value": "fa5252"},
  {"name": "color_red7", "value": "f03e3e"},
  {"name": "color_red8", "value": "e03131"},
  {"name": "color_red9", "value": "c92a2a"},
  {"name": "color_orange0", "value": "fff4e6"},
  {"name": "color_orange1", "value": "ffe8cc"},
  {"name": "color_orange2", "value": "ffd8a8"},
  {"name": "color_orange3", "value": "ffc078"},
  {"name": "color_orange4", "value": "ffa94d"},
  {"name": "color_orange5", "value": "ff922b"},
  {"name": "color_orange6", "value": "fd7e14"},
  {"name": "color_orange7", "value": "f76707"},
  {"name": "color_orange8", "value": "e8590c"},
  {"name": "color_orange9", "value": "d9480f"},
  {"name": "color_yellow0", "value": "343a40"},
  {"name": "color_yellow1", "value": "fff3bf"},
  {"name": "color_yellow2", "value": "ffec99"},
  {"name": "color_yellow3", "value": "ffe066"},
  {"name": "color_yellow4", "value": "ffd43b"},
  {"name": "color_yellow5", "value": "fcc419"},
  {"name": "color_yellow6", "value": "fab005"},
  {"name": "color_yellow7", "value": "f59f00"},
  {"name": "color_yellow8", "value": "f08c00"},
  {"name": "color_yellow9", "value": "e67700"},
  {"name": "color_lime0", "value": "f4fce3"},
  {"name": "color_lime1", "value": "e9fac8"},
  {"name": "color_lime2", "value": "d8f5a2"},
  {"name": "color_lime3", "value": "c0eb75"},
  {"name": "color_lime4", "value": "a9e34b"},
  {"name": "color_lime5", "value": "94d82d"},
  {"name": "color_lime6", "value": "82c91e"},
  {"name": "color_lime7", "value": "74b816"},
  {"name": "color_lime8", "value": "66a80f"},
  {"name": "color_lime9", "value": "5c940d"},
  {"name": "color_green0", "value": "ebfbee"},
  {"name": "color_green1", "value": "d3f9d8"},
  {"name": "color_green2", "value": "b2f2bb"},
  {"name": "color_green3", "value": "8ce99a"},
  {"name": "color_green4", "value": "69db7c"},
  {"name": "color_green5", "value": "51cf66"},
  {"name": "color_green6", "value": "40c057"},
  {"name": "color_green7", "value": "37b24d"},
  {"name": "color_green8", "value": "2f9e44"},
  {"name": "color_green9", "value": "2b8a3e"},
  {"name": "color_teal0", "value": "e6fcf5"},
  {"name": "color_teal1", "value": "c3fae8"},
  {"name": "color_teal2", "value": "96f2d7"},
  {"name": "color_teal3", "value": "63e6be"},
  {"name": "color_teal4", "value": "38d9a9"},
  {"name": "color_teal5", "value": "20c997"},
  {"name": "color_teal6", "value": "12b886"},
  {"name": "color_teal7", "value": "0ca678"},
  {"name": "color_teal8", "value": "099268"},
  {"name": "color_teal9", "value": "087f5b"},
  {"name": "color_cyan0", "value": "e3fafc"},
  {"name": "color_cyan1", "value": "c5f6fa"},
  {"name": "color_cyan2", "value": "99e9f2"},
  {"name": "color_cyan3", "value": "66d9e8"},
  {"name": "color_cyan4", "value": "3bc9db"},
  {"name": "color_cyan5", "value": "22b8cf"},
  {"name": "color_cyan6", "value": "15aabf"},
  {"name": "color_cyan7", "value": "1098ad"},
  {"name": "color_cyan8", "value": "0c8599"},
  {"name": "color_cyan9", "value": "0b7285"}
];
const kLightColors = [
  {"name": "color_black", "value": "000000"},
  {"name": "color_white", "value": "ffffff"},
  {"name": "color_base", "value": "0588cb"},
  {"name": "color_gray0", "value": "f8f9fa"},
  {"name": "color_gray1", "value": "f1f3f5"},
  {"name": "color_gray2", "value": "e9ecef"},
  {"name": "color_gray3", "value": "dee2e6"},
  {"name": "color_gray4", "value": "ced4da"},
  {"name": "color_gray5", "value": "adb5bd"},
  {"name": "color_gray6", "value": "868e96"},
  {"name": "color_gray7", "value": "495057"},
  {"name": "color_gray7_1", "value": "495057"},
  {"name": "color_gray8", "value": "343a40"},
  {"name": "color_gray9", "value": "212529"},
  {"name": "color_blue0", "value": "e7f5ff"},
  {"name": "color_blue1", "value": "c9e8ff"},
  {"name": "color_blue2", "value": "94d1ff"},
  {"name": "color_blue3", "value": "5db8fe"},
  {"name": "color_blue4", "value": "37a6ed"},
  {"name": "color_blue5", "value": "0588cb"},
  {"name": "color_blue6", "value": "0f77b8"},
  {"name": "color_blue7", "value": "056aa6"},
  {"name": "color_blue8", "value": "005f9c"},
  {"name": "color_blue9", "value": "005a99"},
  {"name": "color_indigo0", "value": "edf2ff"},
  {"name": "color_indigo1", "value": "dbe4ff"},
  {"name": "color_indigo2", "value": "bac8ff"},
  {"name": "color_indigo3", "value": "91a7ff"},
  {"name": "color_indigo4", "value": "748ffc"},
  {"name": "color_indigo5", "value": "5c7cfa"},
  {"name": "color_indigo6", "value": "4c6ef5"},
  {"name": "color_indigo7", "value": "4263eb"},
  {"name": "color_indigo8", "value": "3b5bdb"},
  {"name": "color_indigo9", "value": "364fc7"},
  {"name": "color_violet0", "value": "f3f0ff"},
  {"name": "color_violet1", "value": "e5dbff"},
  {"name": "color_violet2", "value": "d0bfff"},
  {"name": "color_violet3", "value": "b197fc"},
  {"name": "color_violet4", "value": "9775fa"},
  {"name": "color_violet5", "value": "845ef7"},
  {"name": "color_violet6", "value": "7950f2"},
  {"name": "color_violet7", "value": "7048e8"},
  {"name": "color_violet8", "value": "6741d9"},
  {"name": "color_violet9", "value": "5f3dc4"},
  {"name": "color_fuchsia0", "value": "f8f0fc"},
  {"name": "color_fuchsia1", "value": "f3d9fa"},
  {"name": "color_fuchsia2", "value": "eebefa"},
  {"name": "color_fuchsia3", "value": "e599f7"},
  {"name": "color_fuchsia4", "value": "da77f2"},
  {"name": "color_fuchsia5", "value": "cc5de8"},
  {"name": "color_fuchsia6", "value": "be4bdb"},
  {"name": "color_fuchsia7", "value": "ae3ec9"},
  {"name": "color_fuchsia8", "value": "9c36b5"},
  {"name": "color_fuchsia9", "value": "862e9c"},
  {"name": "color_pink0", "value": "fff0f6"},
  {"name": "color_pink1", "value": "ffdeeb"},
  {"name": "color_pink2", "value": "fcc2d7"},
  {"name": "color_pink3", "value": "faa2c1"},
  {"name": "color_pink4", "value": "f783ac"},
  {"name": "color_pink5", "value": "f06595"},
  {"name": "color_pink6", "value": "e64980"},
  {"name": "color_pink7", "value": "d6336c"},
  {"name": "color_pink8", "value": "c2255c"},
  {"name": "color_pink9", "value": "a61e4d"},
  {"name": "color_red0", "value": "fff5f5"},
  {"name": "color_red1", "value": "ffe3e3"},
  {"name": "color_red2", "value": "ffc9c9"},
  {"name": "color_red3", "value": "ffa8a8"},
  {"name": "color_red4", "value": "ff8787"},
  {"name": "color_red5", "value": "ff6b6b"},
  {"name": "color_red6", "value": "fa5252"},
  {"name": "color_red7", "value": "f03e3e"},
  {"name": "color_red8", "value": "e03131"},
  {"name": "color_red9", "value": "c92a2a"},
  {"name": "color_orange0", "value": "fff4e6"},
  {"name": "color_orange1", "value": "ffe8cc"},
  {"name": "color_orange2", "value": "ffd8a8"},
  {"name": "color_orange3", "value": "ffc078"},
  {"name": "color_orange4", "value": "ffa94d"},
  {"name": "color_orange5", "value": "ff922b"},
  {"name": "color_orange6", "value": "fd7e14"},
  {"name": "color_orange7", "value": "f76707"},
  {"name": "color_orange8", "value": "e8590c"},
  {"name": "color_orange9", "value": "d9480f"},
  {"name": "color_yellow0", "value": "fff9db"},
  {"name": "color_yellow1", "value": "fff3bf"},
  {"name": "color_yellow2", "value": "ffec99"},
  {"name": "color_yellow3", "value": "ffe066"},
  {"name": "color_yellow4", "value": "ffd43b"},
  {"name": "color_yellow5", "value": "fcc419"},
  {"name": "color_yellow6", "value": "fab005"},
  {"name": "color_yellow7", "value": "f59f00"},
  {"name": "color_yellow8", "value": "f08c00"},
  {"name": "color_yellow9", "value": "e67700"},
  {"name": "color_lime0", "value": "f4fce3"},
  {"name": "color_lime1", "value": "e9fac8"},
  {"name": "color_lime2", "value": "d8f5a2"},
  {"name": "color_lime3", "value": "c0eb75"},
  {"name": "color_lime4", "value": "a9e34b"},
  {"name": "color_lime5", "value": "94d82d"},
  {"name": "color_lime6", "value": "82c91e"},
  {"name": "color_lime7", "value": "74b816"},
  {"name": "color_lime8", "value": "66a80f"},
  {"name": "color_lime9", "value": "5c940d"},
  {"name": "color_green0", "value": "ebfbee"},
  {"name": "color_green1", "value": "d3f9d8"},
  {"name": "color_green2", "value": "b2f2bb"},
  {"name": "color_green3", "value": "8ce99a"},
  {"name": "color_green4", "value": "69db7c"},
  {"name": "color_green5", "value": "51cf66"},
  {"name": "color_green6", "value": "40c057"},
  {"name": "color_green7", "value": "37b24d"},
  {"name": "color_green8", "value": "2f9e44"},
  {"name": "color_green9", "value": "2b8a3e"},
  {"name": "color_teal0", "value": "e6fcf5"},
  {"name": "color_teal1", "value": "c3fae8"},
  {"name": "color_teal2", "value": "96f2d7"},
  {"name": "color_teal3", "value": "63e6be"},
  {"name": "color_teal4", "value": "38d9a9"},
  {"name": "color_teal5", "value": "20c997"},
  {"name": "color_teal6", "value": "12b886"},
  {"name": "color_teal7", "value": "0ca678"},
  {"name": "color_teal8", "value": "099268"},
  {"name": "color_teal9", "value": "087f5b"},
  {"name": "color_cyan0", "value": "e3fafc"},
  {"name": "color_cyan1", "value": "c5f6fa"},
  {"name": "color_cyan2", "value": "99e9f2"},
  {"name": "color_cyan3", "value": "66d9e8"},
  {"name": "color_cyan4", "value": "3bc9db"},
  {"name": "color_cyan5", "value": "22b8cf"},
  {"name": "color_cyan6", "value": "15aabf"},
  {"name": "color_cyan7", "value": "1098ad"},
  {"name": "color_cyan8", "value": "0c8599"},
  {"name": "color_cyan9", "value": "0b7285"}
];

var colors = {
  ThemeMode.dark: {
    for (var color in kDarkColors)
      '${color['name']}': Color(int.parse("0xFF${color['value']}")),
  },
  ThemeMode.light: {
    for (var color in kLightColors)
      '${color['name']}': Color(int.parse("0xFF${color['value']}")),
  },
};

ThemeData _themeData(ThemeMode theme, BuildContext context) {
  return ThemeData(
    primaryColor: colors[theme]!['color_base'],
    scaffoldBackgroundColor: colors[theme]!['color_white'],
    textTheme: Theme.of(context).textTheme.apply(
      bodyColor: colors[theme]!['color_gray7'],
      displayColor: colors[theme]!['color_gray7'],
    ),
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ButtonStyle(
        shape: MaterialStateProperty.all(
          const RoundedRectangleBorder(
            borderRadius: BorderRadius.all(
              Radius.circular(24),
            ),
          ),
        ),
      ),
    ),
  );
}
