#!/bin/bash

#
# Here we make sure we are compiling with the expected
# environment when compiling for Android or iOS.
#
# This script tests the autotools based builds. There
# is another script testing for the OpenSSL case.
#

set -euo pipefail

topdir=$(dirname $(dirname $(dirname $(realpath $0))))

check_for_executable() {
	local name=$1
	local value=$2
	echo -n "checking for $name... " 1>&2
	if [[ ! -x $value ]]; then
		echo "not an executable path: $value" 1>&2
		exit 1
	fi
	echo "$value" 1>&2
}

check_for_variable_value() {
	local name=$1
	local actual_value=$2
	local expected_value=$3
	echo -n "checking for $name... " 1>&2
	if [[ "$actual_value" != "$expected_value" ]]; then
		echo "unexpected value: $actual_value" 1>&2
		exit 1
	fi
	echo "$actual_value" 1>&2
}

case $GOOS in
android)
	case $GOARCH in
	arm64)
		check_for_variable_value CFLAGS "$CFLAGS" "-fdata-sections -ffunction-sections -fstack-protector-strong -funwind-tables -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -fpic -O2 -DANDROID -fsanitize=safe-stack -fsanitize=bounds -fsanitize-undefined-trap-on-error"
		check_for_variable_value CONFIGURE_HOST $CONFIGURE_HOST aarch64-linux-android
		;;
	arm)
		check_for_variable_value CFLAGS "$CFLAGS" "-fdata-sections -ffunction-sections -fstack-protector-strong -funwind-tables -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -fpic -Oz -DANDROID -fsanitize=bounds -fsanitize-undefined-trap-on-error -mthumb"
		check_for_variable_value CONFIGURE_HOST $CONFIGURE_HOST arm-linux-androideabi
		;;

	386)
		check_for_variable_value CFLAGS "$CFLAGS" "-fdata-sections -ffunction-sections -fstack-protector-strong -funwind-tables -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -fPIC -O2 -DANDROID -fsanitize=safe-stack -fstack-clash-protection -fsanitize=bounds -fsanitize-undefined-trap-on-error -mstackrealign"
		check_for_variable_value CONFIGURE_HOST $CONFIGURE_HOST i686-linux-android
		;;

	amd64)
		check_for_variable_value CFLAGS "$CFLAGS" "-fdata-sections -ffunction-sections -fstack-protector-strong -funwind-tables -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -fPIC -O2 -DANDROID -fsanitize=safe-stack -fstack-clash-protection -fsanitize=bounds -fsanitize-undefined-trap-on-error"
		check_for_variable_value CONFIGURE_HOST $CONFIGURE_HOST x86_64-linux-android
		;;

	*)
		echo "FATAL: unsupported \$GOARCH value: $GOARCH" 1>&2
		exit 1
		;;
	esac

	check_for_variable_value DESTDIR "$DESTDIR" "$topdir/internal/libtor/android/$GOARCH"
	check_for_executable AR $AR
	check_for_executable CC $CC
	check_for_executable AS $AS
	check_for_executable CXX $CXX
	check_for_executable LD $LD
	check_for_executable RANLIB $RANLIB
	check_for_executable STRIP $STRIP
	;;

*)
	echo "FATAL: unsupported \$GOOS value: $GOOS" 1>&2
	exit 1
	;;
esac
