#!/bin/sh
set -e
if [ "$GOARCH" = "" ]; then
    echo 'fatal: $GOARCH is not set' 1>&2
    exit 1
fi
set -x
apk update
apk upgrade
apk add --no-progress gcc git linux-headers musl-dev
CGO_ENABLED=1 GOOS=linux go build -o ./CLI/linux/$GOARCH/ \
    -ldflags='-s -w -extldflags "-static"' "$@" ./cmd/ooniprobe
