# Performs miscellaneous quick checks
name: checks
on:
  pull_request:
  push:

jobs:
  perform_code_quality_checks:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ "ubuntu-22.04" ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: ./MOBILE/ios/createpodspecs_test

      - run: ./script/nocopyreadall.bash

      - run: ./script/ghpublish_test.bash
