# Interim build script checking for go1.19
#
# Psiphon not working with go1.19: TODO(https://github.com/ooni/probe/issues/2222)
#
name: go1.19
on:
  pull_request:
  push:
    branches:
      - "master"
      - "release/**"
      - "fullbuild"

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - run: go version

      - run: go build -v ./...

      - run: go test -short -race -tags shaping ./...
