# Interim build script checking for go1.19
#
# Psiphon not working with go1.19: TODO(https://github.com/ooni/probe/issues/2222)
#
name: go1.19
on:
  pull_request:
  push:
    branches:
      - "master"
      - "release/**"
      - "fullbuild"

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - run: go install golang.org/dl/go1.19.1@latest

      - run: $(go env GOPATH)/bin/go1.19.1 download

      - run: $(go env GOPATH)/bin/go1.19.1 build -v ./...

      - run: $(go env GOPATH)/bin/go1.19.1 test -short -race -tags shaping ./...

