# Runs the whole test suite using go1.21
name: alltests-go1.21
on:
  pull_request:
  push:
    branches:
      - "release/**"
      - "fullbuild"
      - "alltestsbuild"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: ~1.21
          cache-key-suffix: "-alltests-go1.21"

      # We cannot run buildtool tests using an unexpected version of Go because the
      # tests check whether we're using the expected version of Go 😂😂😂😂.
      - run: go test -race -tags shaping $(go list ./...|grep -v 'internal/cmd/buildtool')
