# Ensures that ./internal/cmd/buildtool works with different go versions

name: goversion
on:
  push:
    branches:
      - "release/**"
      - "fullbuild"
    tags:
      - "v*"
  schedule:
    - cron: "17 7 * * *"

jobs:
  build_with_unexpected_go_version:
    strategy:
      matrix:
        goversion: ["1.17", "1.18", "1.19", "1.21"]
        system: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: "${{ matrix.system }}"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.goversion }}"

      - run: go run ./internal/cmd/buildtool generic miniooni
