name: Setup Custom Gomobile

on:
  push:
    branches:
      - test/oomobile
  workflow_dispatch:

jobs:
  setup-gomobile:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'  # Adjust as needed

      - name: Install custom gomobile
        run: |
          go install github.com/ooni/oomobile/cmd/gomobile@v0.1.18
          go install github.com/ooni/oomobile/cmd/gobind@v0.1.18
          go get github.com/ooni/oomobile@v0.1.18

      - name: Run gomobile init
        run: |
          gomobile init

      - name: Run gomobile bind
        run: |
          gomobile bind -target=java/amd64 -o oonimkall.jar ./pkg/oonimkall
 