name: Setup Custom Gomobile

on:
  push:
    branches:
      - test/oomobile
  workflow_dispatch:

jobs:
  setup-gomobile:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'  # Adjust as needed

      - name: Install custom gomobile
        run: |
          go install github.com/ooni/oomobile/cmd/gomobile@v0.1.4
          go install github.com/ooni/oomobile/cmd/gobind@v0.1.4
          go get github.com/ooni/oomobile@v0.1.4

      - name: Run gomobile commands with full path
        shell: pwsh
        run: |
          $gomobile = "$env:USERPROFILE\go\bin\gomobile.exe"
          $gobind = "$env:USERPROFILE\go\bin\gobind.exe"

          & $gomobile init -v
          & $gomobile bind -target=java -o oonimkall.jar ./pkg/oonimkall
