# Runs quality assurance checks
name: "qa"
on:
  push:
    branches:
      - "release/**"
      - "fullbuild"
      - "qabuild"

jobs:
  test_webconnectivity:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: ./QA/rundocker.bash "webconnectivity"
