# qahhfm runs QA checks for the hhfm experiment
name: "qahhfm"
on:
  push:
    branches:
      - "release/**"
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.18.2"
      - uses: actions/checkout@v2
      - run: ./QA/rundocker.bash "hhfm"
