# Runs QA checks for the hhfm experiment
name: "qahhfm"
on:
  push:
    branches:
      - "release/**"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Get GOVERSION content
        id: goversion
        run: echo ::set-output name=version::$(cat GOVERSION)

      - uses: actions/setup-go@v1
        with:
          go-version: "${{ steps.goversion.outputs.version }}"

      - run: ./QA/rundocker.bash "hhfm"
