# Runs QA checks for the telegram experiment
name: "qatelegram"
on:
  push:
    branches:
      - "release/**"
      - "fullbuild"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Get GOVERSION content
        id: goversion
        run: echo ::set-output name=version::$(cat GOVERSION)

      - uses: actions/setup-go@v3
        with:
          go-version: "${{ steps.goversion.outputs.version }}"

      - run: ./QA/rundocker.bash "telegram"
