# qatelegram runs QA checks for the telegram experiment
name: "qatelegram"
on:
  push:
    branches:
      - "release/**"
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.17.9"
      - uses: actions/checkout@v2
      - run: ./QA/rundocker.bash "telegram"
